# используем язык java. Travis CI поддерживает разные языки.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false # faster builds

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - ill-jah@yandex.ru
    on_success: never # default: change
    on_failure: never # default: always
    
# Усатновка СУБД для тестов в Travis CI
services:
  - postgresql
  
before_script:
  - psql -c 'create database jpack2p8ch4task2;' -U postgres
  - psql -c 'create database jpack2p9ch7task1;' -U postgres
  - psql -c 'create database jpack2p9ch8task1;' -U postgres
  - psql -c 'create database jpack2p9ch9task1;' -U postgres
  - psql -c 'create database jpack3p1ch1task1;' -U postgres
  - psql -c 'create database jpack3p1ch1task2;' -U postgres
  - psql -c 'create database jpack3p1ch2task1;' -U postgres
  - psql -c 'create database jpack3p1ch2task2;' -U postgres
  - psql -c 'create database jpack3p1ch3task1;' -U postgres