drop table if exists cars_bodies;
drop table if exists bodies;
drop table if exists cars;

create table cars_bodies (
    car_id int not null,
    body_id int not null
);
insert into cars_bodies (car_id, body_id) values (1, 1);
insert into cars_bodies (car_id, body_id) values (1, 2);
insert into cars_bodies (car_id, body_id) values (2, 2);
insert into cars_bodies (car_id, body_id) values (3, 1);
insert into cars_bodies (car_id, body_id) values (4, 6);

create table bodies (
    id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) not null primary key,
    name varchar (16) not null unique
);
insert into bodies (name) values ('sedan');
insert into bodies (name) values ('hatchback');
insert into bodies (name) values ('universal');
insert into bodies (name) values ('crossover');
insert into bodies (name) values ('van');
insert into bodies (name) values ('off-road');

create table cars (
    id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) not null primary key,
    name varchar (32) not null unique
);
insert into cars (name) values ('Focus');
insert into cars (name) values ('Fusion');
insert into cars (name) values ('Aveo');
insert into cars (name) values ('Niva');